# permissions to do viewer batons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baton-viewer-role
rules:
- apiGroups:
  - baton.baton
  resources:
  - batons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baton.baton
  resources:
  - batons/status
  verbs:
  - get
